spring.application.name=devmentor-backend

# MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/devmentor_db
spring.datasource.username=root
spring.datasource.password=WXby@79albe
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Server port
server.port=8080

# FastAPI service URL (Python backend)
fastapi.base.url=http://127.0.0.1:8000

# JWT Secret
jwt.secret=devmentorSecretKeyChangeThisInProduction12345
jwt.expiration=86400000